class FlightBooking {
  // In Pydantic, booking_id is not optional for the main model,
  // but it's typically generated by the DB, so for saving it's not provided.
  // We'll make it nullable here to harmonize, and rely on server for generation.
  final int? bookingId;
  final int flightId;
  final DateTime date; // Use DateTime for dates
  final int payId;
  final int typeId;
  final int holder; // Assuming this is an ID (e.g., Passenger ID)

  FlightBooking({
    this.bookingId,
    required this.flightId,
    required this.date,
    required this.payId,
    required this.typeId,
    required this.holder,
  });

  factory FlightBooking.fromJson(Map<String, dynamic> json) {
    return FlightBooking(
      bookingId: json['booking_id'] as int?,
      flightId: json['flight_id'] as int,
      date: DateTime.parse(json['date'] as String),
      // Parse string to DateTime
      payId: json['pay_id'] as int,
      typeId: json['type_id'] as int,
      holder: json['holder'] as int,
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (bookingId != null) {
      data['booking_id'] = bookingId;
    }
    data['flight_id'] = flightId;
    data['date'] = date
        .toIso8601String(); // Convert DateTime to ISO 8601 string
    data['pay_id'] = payId;
    data['type_id'] = typeId;
    data['holder'] = holder;
    return data;
  }
}
